version: '3.1'

services:

  bugatti-api:
    image: tgalske/bugatti-web
    restart: always
    networks:
      - bugatti-net
    ports:
      - "80:80"
    labels:
      - "traefik.backend=bugatti-web"
      - "traefik.docker.network=bugatti-net"
      - "traefik.enable=true"
      - "traefik.protocol=http"
      - "traefik.frontend.rule=Host:www.thegc.cf"
      - "traefik.port=80"
networks:
  bugatti-net:
    external: true